/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TaskItem: typeof import('./src/components/task-item/index.vue')['default']
    XtButton: typeof import('@pkg/ui/src/button/index.vue')['default']
    XtCard: typeof import('@pkg/ui/src/card/index.vue')['default']
    XtCheckboxButton: typeof import('@pkg/ui/src/checkbox-button/index.vue')['default']
    XtCheckboxButtonGroup: typeof import('@pkg/ui/src/checkbox-button-group/index.vue')['default']
    XtDivider: typeof import('@pkg/ui/src/divider/index.vue')['default']
    XtEmpty: typeof import('@pkg/ui/src/empty/index.vue')['default']
    XtIconClear: typeof import('@pkg/icon/src/clear/index.vue')['default']
    XtIconClose: typeof import('@pkg/icon/src/close/index.vue')['default']
    XtIconCloseOneFilled: typeof import('@pkg/icon/src/close-one-filled/index.vue')['default']
    XtIconDownTwo: typeof import('@pkg/icon/src/down-two/index.vue')['default']
    XtIconFilter: typeof import('@pkg/icon/src/filter/index.vue')['default']
    XtIconLeft: typeof import('@pkg/icon/src/left/index.vue')['default']
    XtIconPlayFilled: typeof import('@pkg/icon/src/play-filled/index.vue')['default']
    XtIconRight: typeof import('@pkg/icon/src/right/index.vue')['default']
    XtIconSearch: typeof import('@pkg/icon/src/search/index.vue')['default']
    XtLink: typeof import('@pkg/ui/src/link/index.vue')['default']
    XtPopup: typeof import('@pkg/ui/src/popup/index.vue')['default']
    XtSearch: typeof import('@pkg/ui/src/search/index.vue')['default']
    XtSelectPopup: typeof import('@pkg/ui/src/select-popup/index.vue')['default']
    XtSpace: typeof import('@pkg/ui/src/space/index.vue')['default']
    XtSticky: typeof import('@pkg/ui/src/sticky/index.vue')['default']
    XtTabs: typeof import('@pkg/ui/src/tabs/index.vue')['default']
    XtTag: typeof import('@pkg/ui/src/tag/index.vue')['default']
    XtText: typeof import('@pkg/ui/src/text/index.vue')['default']
  }
}
